Grappling hook
rplazevedo/2DSwingingPlatformer pull request #3
Opened 2023-12-09 12:50 UTC by rplazevedo

Added grappling hook mecahnics

2023-12-09 13:03 UTC, DanielRussom requested changes
Looks good, a few questions / comments ♥

2023-12-09 13:03 UTC, DanielRussom commented on Assets/Scripts/Player.cs
> +    void DrawLine()
Is this used in other files? Can it be made Private?

2023-12-09 13:03 UTC, DanielRussom commented on Assets/Scripts/Player.cs
> +        var connectedAnchor = new Vector3(distanceJoint.connectedAnchor.x, distanceJoint.connectedAnchor.y, 0);
Why do we create a Vector3 here, and then seemingly create it again in ` lineRenderer.SetPosition(1, new Vector3(connectedAnchor.x, connectedAnchor.y, 0));` ? 
I might be missing something, is this doing the same thing?

2023-12-09 13:03 UTC, DanielRussom commented on Assets/Scripts/Player.cs
> +    void DrawLine()
++ Move DrawLine above DetachGrappleOnClick (since it's called first in Grapple()) ;3

2023-12-09 22:22 UTC, rplazevedo commented on Assets/Scripts/Player.cs
> +        else if (_isGrappled)
I don't want to run call DrawLine if it is not grappled. Also dopn't need to check for detach grapple

2023-12-09 22:29 UTC, rplazevedo commented on Assets/Scripts/Player.cs
> +    void DrawLine()
Totatlly fixes 100% no tests needed

2023-12-09 22:29 UTC, rplazevedo commented on Assets/Scripts/Player.cs
> +    void DrawLine()
Source: trust me, bro

2023-12-10 13:05 UTC, DanielRussom approved these changes

2023-12-10 13:06 UTC, merged